import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "./screen/navbar/navbar";
import "bootstrap/dist/css/bootstrap.css";
import 'react-toastify/dist/ReactToastify.css';

import dynamic from "next/dynamic";
import { Box } from "@mui/material";
import bg from "./assets/background.png";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const MyDynamicComponent = dynamic(() => import("./screen/navbar/navbar"));

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <main
          style={{
            position:'absolute',
            backgroundImage: `url(${bg.src})`,
            height: "100vh",
            margin: 0,
            padding: 0,
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            width: "100vw",
          }}
        >
        <ToastContainer />
          {typeof window !== "undefined" && <MyDynamicComponent />}
        </main>
      </main>
    </>
  );
}
